---
title: 
keywords: 
description: 
url: https://gdemir.github.io
permalink: "/categories/:categories/:title/"
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions:
  - smart
author: 
editor: 
email: 
cv: 
disqus: 
github: gdemir
trello: 
linkedin: 
googleplus: 
googleanalyticsid: 
twitter: 
facebook: 
instagram: 
foursquare: 
stack: 
