---
title: Gökhan Demir
keywords: Gökhan Demir, Bilgisayar Mühendisi
description: Gökhan Demir
baseurl: 
url: https://gdemir.github.io
permalink: "/categories/:categories/:title/"
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions:
  - smart
author: Gökhan Demir
editor: vim
email: gdemir3327@gmail.com
cv: 
disqus: 
github: gdemir
trello: 
linkedin: in/gdemir
googleanalyticsid: 
twitter: 
facebook: 
instagram: 
foursquare: 
stack: '19107636'
